export const ratingMovies = {
  results: [
    {
      backdrop_path: "/se5Hxz7PArQZOG3Nx2bpfOhLhtV.jpg",
      id: 9806,
      original_title: "The Incredibles",
      overview:
        "Bob Parr has given up his superhero days to log in time as an insurance adjuster and raise his three children with his formerly heroic wife in suburbia. But when he receives a mysterious assignment, it's time to get back into costume.",
      popularity: 71.477,
      poster_path: "/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg",
      release_date: "2004-10-27",
      title: "The Incredibles",
    },
    {
      backdrop_path: "/8eRscFbRYl681zDfkjv1jjW1KAA.jpg",
      id: 1452,
      original_language: "en",
      original_title: "Superman Returns",
      overview:
        "Superman returns to discover his 5-year absence has allowed Lex Luthor to walk free, and that those he was closest to felt abandoned and have moved on. Luthor plots his ultimate revenge that could see millions killed and change the face of the planet forever, as well as ridding himself of the Man of Steel.",
      popularity: 23.183,
      poster_path: "/385XwTQZDpRX2d3kxtnpiLrjBXw.jpg",
      release_date: "2006-06-28",
      title: "Superman Returns",
    },
    {
      backdrop_path: "/xh0ZRdnL4pSqfW73HBf97xiNEFP.jpg",
      id: 8960,
      original_language: "en",
      original_title: "Hancock",
      overview:
        "Hancock is a down-and-out superhero who's forced to employ a PR expert to help repair his image when the public grows weary of all the damage he's inflicted during his lifesaving heroics. The agent's idea of imprisoning the antihero to make the world miss him proves successful, but will Hancock stick to his new sense of purpose or slip back into old habits?",
      popularity: 53.556,
      poster_path: "/7DyuV2G0hLEqHeueDfOqhZ2DVut.jpg",
      release_date: "2008-07-01",
      title: "Hancock",
    },
    {
      backdrop_path: "/2Gq4teAIkVVv0kc6JsfU66C3VOJ.jpg",
      id: 9741,
      original_language: "en",
      original_title: "Unbreakable",
      overview:
        "An ordinary man makes an extraordinary discovery when a train accident leaves his fellow passengers dead — and him unscathed. The answer to this mystery could lie with the mysterious Elijah Price, a man who suffers from a disease that renders his bones as fragile as glass.",
      popularity: 24.491,
      poster_path: "/mLuehrGLiK5zFCyRmDDOH6gbfPf.jpg",
      release_date: "2000-11-22",
      title: "Unbreakable",
    },
    {
      backdrop_path: "/l4QHerTSbMI7qgvasqxP36pqjN6.jpg",
      id: 603,
      original_language: "en",
      original_title: "The Matrix",
      overview:
        "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
      popularity: 79.309,
      poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
      release_date: "1999-03-30",
      title: "The Matrix",
    },
    {
      backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
      id: 424,
      original_language: "en",
      original_title: "Schindler's List",
      overview:
        "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
      popularity: 51.98,
      poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
      release_date: "1993-12-15",
      title: "Schindler's List",
    },
    {
      backdrop_path: "/6ms6RdNcQUAnjBY26aM85xC2wV0.jpg",
      id: 7191,
      original_language: "en",
      original_title: "Cloverfield",
      overview:
        "Five young New Yorkers throw their friend a going-away party the night that a monster the size of a skyscraper descends upon the city. Told from the point of view of their video camera, the film is a document of their attempt to survive the most surreal, horrifying event of their lives.",
      popularity: 31.474,
      poster_path: "/qIegUGJqyMMCRjkKV1s7A9MqdJ8.jpg",
      release_date: "2008-01-15",
      title: "Cloverfield",
    },
    {
      backdrop_path: "/wh4ze6klUbeichAj603OKZwY1W5.jpg",
      id: 218,
      original_language: "en",
      original_title: "The Terminator",
      overview:
        'In the post-apocalyptic future, reigning tyrannical supercomputers teleport a cyborg assassin known as the "Terminator" back to 1984 to kill Sarah Connor, whose unborn son is destined to lead insurgents against 21st century mechanical hegemony. Meanwhile, the human-resistance movement dispatches a lone warrior to safeguard Sarah. Can he stop the virtually indestructible killing machine?',
      popularity: 45.608,
      poster_path: "/kdYu7YJJP0uuGEuhUX5toqvBSog.jpg",
      release_date: "1984-10-26",
      title: "The Terminator",
    },
    {
      backdrop_path: "/P4bGyJQF0shAcRku3I2perNUQR.jpg",
      id: 23483,
      original_language: "en",
      original_title: "Kick-Ass",
      overview:
        "Dave Lizewski is an unnoticed high school student and comic book fan who one day decides to become a super-hero, even though he has no powers, training or meaningful reason to do so.",
      popularity: 46.304,
      poster_path: "/8citjdBmjddZjlPsAHEyCKwGVvD.jpg",
      release_date: "2010-03-22",
      title: "Kick-Ass",
    },
    {
      backdrop_path: "/jMBpJFRtrtIXymer93XLavPwI3P.jpg",
      id: 679,
      original_language: "en",
      original_title: "Aliens",
      overview:
        "When Ripley's lifepod is found by a salvage crew over 50 years later, she finds that terra-formers are on the very planet they found the alien species. When the company sends a family of colonists out to investigate her story—all contact is lost with the planet and colonists. They enlist Ripley and the colonial marines to return and search for answers.",
      popularity: 45.005,
      poster_path: "/r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg",
      release_date: "1986-07-18",
      title: "Aliens",
    },
    {
      backdrop_path: "/4ywKTlsIllvQYRiZJPwYACJIHY8.jpg",
      id: 489,
      original_language: "en",
      original_title: "Good Will Hunting",
      overview:
        "Will Hunting has a genius-level IQ but chooses to work as a janitor at MIT. When he solves a difficult graduate-level math problem, his talents are discovered by Professor Gerald Lambeau, who decides to help the misguided youth reach his potential. When Will is arrested for attacking a police officer, Professor Lambeau makes a deal to get leniency for him if he will get treatment from therapist Sean Maguire.",
      popularity: 44.795,
      poster_path: "/bABCBKYBK7A5G1x0FzoeoNfuj2.jpg",
      release_date: "1997-12-05",
      title: "Good Will Hunting",
    },
    {
      backdrop_path: "/vVBcIN68kFq681b4lObiNJhEVro.jpg",
      id: 453,
      original_language: "en",
      original_title: "A Beautiful Mind",
      overview:
        "John Nash is a brilliant but asocial mathematician fighting schizophrenia. After he accepts secret work in cryptography, his life takes a turn for the nightmarish.",
      popularity: 27.447,
      poster_path: "/zwzWCmH72OSC9NA0ipoqw5Zjya8.jpg",
      release_date: "2001-12-11",
      title: "A Beautiful Mind",
    },
    {
      backdrop_path: "/hh28CTWLdxTXA5yJgefZ6gUnFDo.jpg",
      id: 807,
      original_language: "en",
      original_title: "Se7en",
      overview:
        'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
      popularity: 42.809,
      poster_path: "/6yoghtyTpznpBik8EngEmJskVUO.jpg",
      release_date: "1995-09-22",
      title: "Se7en",
    },
    {
      backdrop_path: "/qq4H9JfBKQ5DarMLI6lhUQjn9D7.jpg",
      id: 180,
      original_language: "en",
      original_title: "Minority Report",
      overview:
        "John Anderton is a top 'Precrime' cop in the late-21st century, when technology can predict crimes before they're committed. But Anderton becomes the quarry when another investigator targets him for a murder charge.",
      popularity: 25.998,
      poster_path: "/ccqpHq5tk5W4ymbSbuoy4uYOxFI.jpg",
      release_date: "2002-06-20",
      title: "Minority Report",
    },
    {
      backdrop_path: "/9LSsSPbP715XT9B7acIZzantPyX.jpg",
      id: 73,
      original_language: "en",
      original_title: "American History X",
      overview:
        "Derek Vineyard is paroled after serving 3 years in prison for killing two African-American men. Through his brother, Danny Vineyard's narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.",
      popularity: 29.943,
      poster_path: "/c2gsmSQ2Cqv8zosqKOCwRS0GFBS.jpg",
      release_date: "1998-07-01",
      title: "American History X",
    },
    {
      backdrop_path: "/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg",
      id: 19995,
      original_language: "en",
      original_title: "Avatar",
      overview:
        "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
      popularity: 201.185,
      poster_path: "/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
      release_date: "2009-12-15",
      title: "Avatar",
    },
    {
      backdrop_path: "/8AE7M2lMsyvowfT36porzGtmOtI.jpg",
      id: 38,
      original_language: "en",
      original_title: "Eternal Sunshine of the Spotless Mind",
      overview:
        "Joel Barish, heartbroken that his girlfriend underwent a procedure to erase him from her memory, decides to do the same. However, as he watches his memories of her fade away, he realises that he still loves her, and may be too late to correct his mistake.",
      popularity: 36.729,
      poster_path: "/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
      release_date: "2004-03-19",
      title: "Eternal Sunshine of the Spotless Mind",
    },
    {
      backdrop_path: "/eIi3klFf7mp3oL5EEF4mLIDs26r.jpg",
      id: 78,
      original_language: "en",
      original_title: "Blade Runner",
      overview:
        "In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to terminate a quartet of replicants who have escaped to Earth seeking their creator for a way to extend their short life spans.",
      popularity: 47.122,
      poster_path: "/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg",
      release_date: "1982-06-25",
      title: "Blade Runner",
    },
    {
      backdrop_path: "/fK5ssgvtI43z19FoWigdlqgpLRE.jpg",
      id: 10681,
      original_language: "en",
      original_title: "WALL·E",
      overview:
        "WALL·E is the last robot left on an Earth that has been overrun with garbage and all humans have fled to outer space. For 700 years he has continued to try and clean up the mess, but has developed some rather interesting human-like qualities. When a ship arrives with a sleek new type of robot, WALL·E thinks he's finally found a friend and stows away on the ship when it leaves.",
      popularity: 72.81,
      poster_path: "/Agc6lw8pb6BIGVeguvdjDT0p9Mb.jpg",
      release_date: "2008-06-22",
      title: "WALL·E",
    },
    {
      backdrop_path: "/aDYSnJAK0BTVeE8osOy22Kz3SXY.jpg",
      id: 11,
      original_language: "en",
      original_title: "Star Wars",
      overview:
        "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
      popularity: 81.207,
      poster_path: "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
      release_date: "1977-05-25",
      title: "Star Wars",
    },
  ],
};

export const ratingSeries = {
  results: [
    {
      backdrop_path: "/bsNm9z2TJfe0WO3RedPGWQ8mG1X.jpg",
      id: 1396,
      name: "Breaking Bad",
      original_language: "en",
      original_name: "Breaking Bad",
      overview:
        "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
      poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
      first_air_date: "2008-01-20",
      vote_average: 8.878,
      vote_count: 11544,
    },
    {
      backdrop_path: "/wvdWb5kTQipdMDqCclC6Y3zr4j3.jpg",
      id: 1402,
      name: "The Walking Dead",
      original_language: "en",
      original_name: "The Walking Dead",
      overview:
        "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
      poster_path: "/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
      first_air_date: "2010-10-31",
      vote_average: 8.117,
      vote_count: 14869,
    },
    {
      backdrop_path: "/lHe8iwM4Cdm6RSEiara4PN8ZcBd.jpg",
      id: 44217,
      name: "Vikings",
      original_language: "en",
      original_name: "Vikings",
      overview:
        "The adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.",
      poster_path: "/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg",
      first_air_date: "2013-03-03",
      vote_average: 8.079,
      vote_count: 6130,
    },
    {
      backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      id: 66732,
      name: "Stranger Things",
      original_language: "en",
      original_name: "Stranger Things",
      overview:
        "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
      poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",

      first_air_date: "2016-07-15",
      vote_average: 8.635,
      vote_count: 15438,
    },
    {
      backdrop_path: "/vXpeJJs1z8OKC88CNJX9O9QOhtr.jpg",
      id: 94997,
      name: "House of the Dragon",
      original_language: "en",
      original_name: "House of the Dragon",
      overview:
        "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
      poster_path: "/1X4h40fcB4WWUmIBK0auT4zRBAV.jpg",
      first_air_date: "2022-08-21",
      vote_average: 8.481,
      vote_count: 3091,
    },
    {
      backdrop_path: "/xZUZ9i6vVayjyhR1vRo9Bjku4h.jpg",
      id: 63174,
      name: "Lucifer",
      original_language: "en",
      original_name: "Lucifer",
      overview:
        "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
      poster_path: "/ekZobS8isE6mA53RAiGDG93hBxL.jpg",
      first_air_date: "2016-01-25",
      vote_average: 8.489,
      vote_count: 13422,
    },
    {
      backdrop_path: "/8X1BTSaUyF5rc0malaaQovpxC3f.jpg",
      id: 1418,
      name: "The Big Bang Theory",
      original_language: "en",
      original_name: "The Big Bang Theory",
      overview:
        "The sitcom is centered on five characters living in Pasadena, California: roommates Leonard Hofstadter and Sheldon Cooper; Penny, a waitress and aspiring actress who lives across the hall; and Leonard and Sheldon's equally geeky and socially awkward friends and co-workers, mechanical engineer Howard Wolowitz and astrophysicist Raj Koothrappali. The geekiness and intellect of the four guys is contrasted for comic effect with Penny's social skills and common sense.",
      poster_path: "/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg",
      first_air_date: "2007-09-24",
      vote_average: 7.88,
      vote_count: 9898,
    },
    {
      backdrop_path: "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
      id: 71446,
      name: "Money Heist",
      original_language: "es",
      original_name: "La Casa de Papel",
      overview:
        "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
      poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
      first_air_date: "2017-05-02",
      vote_average: 8.262,
      vote_count: 17484,
    },
    {
      backdrop_path: "/gFkHcIh7iE5G0oVOgpmY8ONQjhl.jpg",
      id: 60735,
      name: "The Flash",
      original_language: "en",
      original_name: "The Flash",
      overview:
        'After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only "meta-human" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won\'t be long before the world learns what Barry Allen has become...The Flash.',
      poster_path: "/rg8N7x27Ef6PvlIiioLStf9ZaIO.jpg",
      first_air_date: "2014-10-07",
      vote_average: 7.797,
      vote_count: 10367,
    },
    {
      backdrop_path: "/hTExot1sfn7dHZjGrk0Aiwpntxt.jpg",
      id: 48866,
      name: "The 100",
      original_language: "en",
      original_name: "The 100",
      overview:
        "100 years in the future, when the Earth has been abandoned due to radioactivity, the last surviving humans live on an ark orbiting the planet — but the ark won't last forever. So the repressive regime picks 100 expendable juvenile delinquents to send down to Earth to see if the planet is still habitable.",
      poster_path: "/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg",
      first_air_date: "2014-03-19",
      vote_average: 7.916,
      vote_count: 7464,
    },
    {
      backdrop_path: "/20eIP9o5ebArmu2HxJutaBjhLf4.jpg",
      id: 87108,
      name: "Chernobyl",
      original_language: "en",
      original_name: "Chernobyl",
      overview:
        "The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.",
      poster_path: "/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
      first_air_date: "2019-05-06",
      vote_average: 8.631,
      vote_count: 4951,
    },
    {
      backdrop_path: "/hmLTIRtVyTHShJl2Wb8LHmvUgJm.jpg",
      id: 19885,
      name: "Sherlock",
      original_language: "en",
      original_name: "Sherlock",
      overview:
        "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
      poster_path: "/7WTsnHkbA0FaG6R9twfFde0I9hl.jpg",
      first_air_date: "2010-07-25",
      vote_average: 8.534,
      vote_count: 4423,
    },
    {
      backdrop_path: "/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
      id: 60574,
      name: "Peaky Blinders",
      original_language: "en",
      original_name: "Peaky Blinders",
      overview:
        "A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.",
      poster_path: "/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
      first_air_date: "2013-09-12",
      vote_average: 8.549,
      vote_count: 8314,
    },
    {
      backdrop_path: "/uNyEVSPeAtJgUBehuQJ8WEFwatN.jpg",
      id: 456,
      name: "The Simpsons",
      original_language: "en",
      original_name: "The Simpsons",
      overview:
        "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
      poster_path: "/zI3E2a3WYma5w8emI35mgq5Iurx.jpg",
      first_air_date: "1989-12-17",
      vote_average: 7.992,
      vote_count: 8782,
    },
    {
      backdrop_path: "/nVRyd8hlg0ZLxBn9RaI7mUMQLnz.jpg",
      id: 1622,
      name: "Supernatural",
      original_language: "en",
      original_name: "Supernatural",
      overview:
        "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way. ",
      poster_path: "/KoYWXbnYuS3b0GyQPkbuexlVK9.jpg",
      first_air_date: "2005-09-13",
      vote_average: 8.304,
      vote_count: 6649,
    },
    {
      backdrop_path: "/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
      id: 1668,
      name: "Friends",
      original_language: "en",
      original_name: "Friends",
      overview:
        "Six young people from New York City, on their own and struggling to survive in the real world, find the companionship, comfort and support they get from each other to be the perfect antidote to the pressures of life.",
      poster_path: "/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
      first_air_date: "1994-09-22",
      vote_average: 8.5,
      vote_count: 6823,
    },
    {
      backdrop_path: "/ci6HNWyJxZ3zrn0AefMb4uUdEKp.jpg",
      id: 63247,
      name: "Westworld",
      original_language: "en",
      original_name: "Westworld",
      overview:
        "A dark odyssey about the dawn of artificial consciousness and the evolution of sin. Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite, no matter how noble or depraved, can be indulged.",
      poster_path: "/ALlSU9du9iRiKIIoY1sREGNqQ5.jpg",
      first_air_date: "2016-10-02",
      vote_average: 8.089,
      vote_count: 4731,
    },
    {
      backdrop_path: "/thLAoL6VeZGmCyDpCOeoxLvA8yS.jpg",
      id: 76479,
      name: "The Boys",
      original_language: "en",
      original_name: "The Boys",
      overview:
        "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
      poster_path: "/ut4PhX7OP2l2oJhrIUYWnt9pnQU.jpg",
      first_air_date: "2019-07-25",
      vote_average: 8.471,
      vote_count: 8245,
    },
    {
      backdrop_path: "/uGy4DCmM33I7l86W7iCskNkvmLD.jpg",
      id: 60625,
      name: "Rick and Morty",
      original_language: "en",
      original_name: "Rick and Morty",
      overview:
        "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
      poster_path: "/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg",
      first_air_date: "2013-12-02",
      vote_average: 8.72,
      vote_count: 8149,
    },
    {
      backdrop_path: "/cJYLon9ejKJV7ua03ab8Tj9u067.jpg",
      id: 18165,
      name: "The Vampire Diaries",
      original_language: "en",
      original_name: "The Vampire Diaries",
      overview:
        "The story of two vampire brothers obsessed with the same girl, who bears a striking resemblance to the beautiful but ruthless vampire they knew and loved in 1864.",
      poster_path: "/xnow2L5YZTo36T4koZs24zU5oqa.jpg",
      first_air_date: "2009-09-10",
      vote_average: 8.34,
      vote_count: 8080,
    },
    {
      backdrop_path: "/bZGAX8oMDm3Mo5i0ZPKh9G2OcaO.jpg",
      id: 84958,
      name: "Loki",
      original_language: "en",
      original_name: "Loki",
      overview:
        "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.",
      poster_path: "/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
      first_air_date: "2021-06-09",
      vote_average: 8.169,
      vote_count: 9812,
    },
  ],
};

export const options = {
  method: "GET",
  headers: {
    accept: "application/json",
    Authorization:
      "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzZjczMmVmZDM0YzI1ZDRiNTQ5ZTZhN2UwMDRmZTcwMSIsInN1YiI6IjY0Yjg0OTRlNGQyM2RkMDEwNjk1Y2ZjMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.LwDNqmYOmsq4hFCbLSoFSJQoXm-f7Mu4qcRM_z5a3DA",
  },
};

export const image_url = "https://image.tmdb.org/t/p/original";
export const image_url_500 = "https://image.tmdb.org/t/p/w300";
export const base_url = "https://api.themoviedb.org/3/search/movie";
export const api_url = "https://api.themoviedb.org/3";
export const api_key = "3f732efd34c25d4b549e6a7e004fe701"; 
export const url_trailer = "https://www.youtube.com/watch?v="
